kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: cfc-festival-staging
spec:
  type: LoadBalancer
  selector:
    app: server
    environment: staging
  ports:
    -
      protocol: "TCP"
      port: 80
      targetPort: 9000
