kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: cfc-festival
spec:
  type: LoadBalancer
  selector:
    app: server
    environment: production
  ports:
    -
      protocol: "TCP"
      port: 80
      targetPort: 9000
