kind: Service
apiVersion: v1
metadata:
  name: reverse-proxy
  namespace: cfc-festival-staging
spec:
  selector:
    app: proxy
    environment: staging
  ports:
    -
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30092
  loadBalancerIP: 104.155.238.192
  type: LoadBalancer
