kind: Service
apiVersion: v1
metadata:
  name: reverse-proxy
spec:
  selector:
    app: proxy
  ports:
    -
      protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30091
  loadBalancerIP: 104.199.129.176
  type: LoadBalancer
